import time

from com.android.monkeyrunner import MonkeyRunner
from com.android.monkeyrunner import MonkeyDevice

device = MonkeyRunner.waitForConnection()

def camera_record(device, MonkeyDevice, MonkeyRunner):
    print("Running camera record activity")
    device.touch(533, 1704, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(334, 612, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(320, 1760, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(2.0)
    device.touch(310, 1792, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(6.0)
    device.touch(519, 1780, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(2.0)
    device.press("KEYCODE_HOME", MonkeyDevice.DOWN_AND_UP)

def gallary_record(device, MonkeyDevice, MonkeyRunner):
    print("Running gallary record activity")
    device.touch(540, 1696, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(118, 608, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(165, 444, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(914, 1832, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(877, 1032, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(87, 72, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.press("KEYCODE_HOME", MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)

def calculator_record(device, MonkeyDevice, MonkeyRunner):
    print("Running calculator record activity")
    device.touch(553, 1728, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(941, 620, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(141, 1604, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(394, 1600, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(644, 1616, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(158, 1412, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(428, 1440, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(634, 1376, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(951, 1164, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(141, 1172, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(408, 1204, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(651, 1176, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(155, 1444, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(388, 1432, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(644, 1368, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(951, 1780, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(172, 964, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.press("KEYCODE_HOME", MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)

def dialer_record(device, MonkeyDevice, MonkeyRunner):
    print("Running dialer record activity")
    device.touch(536, 1708, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(148, 312, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(950, 1750, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(199, 1064, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(543, 1060, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(867, 1096, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(182, 1260, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(560, 1244, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(897, 1232, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(219, 1412, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(536, 1432, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(914, 1408, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(0.2)
    device.touch(992, 872, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(816, 228, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(381, 656, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.press("KEYCODE_HOME", MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)

def chrome_record(device, MonkeyDevice, MonkeyRunner):
    print("Running chrome record activity")
    device.touch(533, 1708, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(735, 304, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(796, 1852, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(779, 1848, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(799, 1852, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(928, 1008, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.touch(907, 600, MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)
    device.press("KEYCODE_HOME", MonkeyDevice.DOWN_AND_UP)
    MonkeyRunner.sleep(1.0)

def run_automated_seq():
    camera_record(device, MonkeyDevice, MonkeyRunner)
    time.sleep(2)
    gallary_record(device, MonkeyDevice, MonkeyRunner)
    time.sleep(1)
    calculator_record(device, MonkeyDevice, MonkeyRunner)
    time.sleep(1)
    dialer_record(device, MonkeyDevice, MonkeyRunner)
    time.sleep(5)
    chrome_record(device, MonkeyDevice, MonkeyRunner)
    time.sleep(4)

if __name__ == "__main__":
    run_automated_seq()